### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by Musyanon** [denisio/Dayz-Epoch-Linux-Server#10]
Above all thank you for the tutorial, everything works fine!
I'd like to know if it is possible to make a self restart every two hours? If yes, how?

Why I can not start the server as follows:
/home/server/arma2/./restarter.pl

It makes me this error:
Can't found server binary!

Should I be mandatory in the arma2 folder for start restarter.pl ?

Thanks

**Comment by WopperTheCat** [comment]
Quote from Denisio:

1) You need to use crontab (for example, restart each 4 hours):
$ echo $HOME
$ crontab -e
0 */4 \* \* \* /home/your_ssh_login/epoch/restarter.pl
2) Check it:
$ crontab -l
3) Edit "restarter.pl":
use constant PATH => '/home/your_ssh_login/epoch/';
