### ISSUE TITLE
"Segmentation fault" on Debiant System

### ISSUE THREAD

**Issue by AnnoDomine** [denisio/Dayz-Epoch-Linux-Server#11]
Hi Devs.

I have install DayZ Mod with ure tutorial and got the Problem when i start epoch.sh comes Segmentation fault.
I use Debiant on my server.
The $ ldd epoch write:

statically linked

The Libarys are complet installed.

Anyone a Tip what i can do?

Grezz Dominic

E.C.: Sorry for my bad english :D

**Comment by JPPWeber** [comment]
Hello,

check your directory.

Mostly it is because there are still directories eith capital letters.

Use the "tolower" programm and check it manualy afterwards.

In my case there where as an example:

expansion
Expansion

So you have to delete the capital one, but first check for content.

Greetings from germany

**Comment by AnnoDomine** [comment]
Alle Buchstaben sind klein geschrieben.

Sowohl über die epoch.sh als auch über den restarter schmeißt er mir folgende dumb.log aus.
Kannst dir hier mal ansehen:

http://amarok-online.eu/dump.log

Server läuft in chroot unter Debaint 7

**Comment by JPPWeber** [comment]
Hast du Arma2 mit im Arma2OA Ordner?
Wenn ja, direkt im AddOns Ordner oder seperat?
Wie sehen deine Startparameter aus?

Do you got the Arma2 content in the arma2oa folder?
If yes, is it directly in the addons folder or in a seperate folder?
Show me your startparams please.

**Comment by AnnoDomine** [comment]
ich hab lediglich den arma 2 oa ordner hoch gejagt, da ich arma 2 free habe.
dato hab ich arma 2 free nicht oben.

die parameter sind die aus der sh datei:

```
export LD_LIBRARY_PATH=.:/usr/lib32:$LD_LIBRARY_PATH;./epoch -server -mod="@dayz_epoch;@dayz_epoch_server;" -config="cfgdayz/server.cfg" -cfg="cfgdayz/basic.cfg" -port=2302 -beta="expansion/beta;expansion/beta/expansion" -noSound -noPause -world=Napf -profiles=cfgdayz -name=cfgdayz -cpucount=2 -exThreads=3 -showscripterrors -pid=2302.pid 2>&1 | ./writer.pl
```

Gegenfrage. hast du TS3? dann schick ich dir die Daten, damit du joinen kannst. Dort lässt sich das glaub ich schneller lösen, bzw besser erklären.

**Comment by Nanakie** [comment]
vieleicht hift ja die odnerstruktur weiter
http://amarok-online.eu/dir.txt

**Comment by Nanakie** [comment]
sonst ist alles von https://github.com/denisio/Dayz-Epoch-Linux-Server befolgt worden

**Comment by JPPWeber** [comment]
Wenn du Arma2 Content nutzt, brauchst du auch den Arma2 AddOns Ordner ;)
Chernarus = Arma2

If you use Arma2 Content, you need the Arma2 AddOns folder.
Chernarus = Arma2

**Comment by JPPWeber** [comment]
Ich bin noch bei der Arbeit, aber wenn du willst, kannst du mich auf meinem TS3 nacher besuchen.
TS3: jppweber.de

**Comment by JPPWeber** [comment]
Warum schreibst du als zwei verschiedene Nutzer?

**Comment by AnnoDomine** [comment]
Wir sind 2 Admins

**Comment by Nanakie** [comment]
server an sich läuft nun nur das connecten funktioiert noch nicht so wirklich sind aber grad noch am basteln^^

das bisherige probelm lag am hauptordner da der noch gross geschrieben war

**Comment by Nanakie** [comment]
so server läuft nun
einziges "problem" wenn einer versucht auf dem server zu konnecten crasht er mit 
File mpmissions__cur_mp.napf\mission.sqm, line 1346: '/Mission/Sensors/Item0.expActiv': Missing ';' at the end of line
18:33:52 Error context ] spawn player_traderCity;";
File mpmissions__cur_mp.napf\mission.sqm, line 1346: '/Mission/Sensors/Item0.enter': '"' encountered instead of '='

in der besagten datei steht nur expCond="(player distance Lenz) < 50;";

mit dem löschen der kompletten klasse class Sensors läuft er

**Comment by AnnoDomine** [comment]
Man kann aber dadurch nicht die Trader nutzen. Sie stehen zwar da, aber es gibt weder eine Savezone, noch ist das Trademenu aufrufbar.

Auch wenn wir den Trader LENZ löschen aus der class, kommt das gleiche Problem, mit dem nächsten Trader. Ich gehe in der Annahme, dass es sich entweder um die Savezone oder um das Tradermenu handelt, da wie besagt, beides nicht geht, wenn wir die class löschen.

**Comment by JPPWeber** [comment]
Wenn das Actionmenü nicht erscheint, liegt dass an einem Fehler in der Missionsdatei, da dort die Actionmenüs definiert werden. Ich denke nicht dass es an der DB liegt.

Abgesehen davon, ist es immer eine schlechte Idee irgendwas zu löschen weil es nicht geht.

**Comment by AnnoDomine** [comment]
Bei dem löschen ging es auch erstmal darum zu gucken, wo es in der class liegt, dass der server abschmiert.
Die Missionsdatei habe ich von der HP von NAPF direkt heruntergeladen.

Was mir merkwürdig erscheint, ist dass der Server auf ARMA 2 Vers: 102451 läuft, wir aber die Daten von 103718 aufgespielt haben. Dazu zeigt mir DayZ-Commander nicht die EPOCH Version an. Kann es ggf daran liegen, das der Server unter eine "alte" Version läuft?

Leider ist Nanakie noch nicht online, um genauer nach zu sehen.

**Comment by AnnoDomine** [comment]
Hier auch mal der Serverlog:

```
20.03.2014, 13:35:59 BattlEye Server: Initialized (v1.185)
20.03.2014, 13:35:59 Host identity created.
20.03.2014, 13:37:39 [KDFW] Anno uses modified data file
20.03.2014, 13:37:39 BattlEye Server: Player #0 [KDFW] Anno (78.42.34.90:2304) connected
20.03.2014, 13:37:39 Player [KDFW] Anno connecting.
20.03.2014, 13:37:39 Mission DayZ Epoch Napf read from bank.
20.03.2014, 13:39:30 BattlEye Server: Initialized (v1.185)
20.03.2014, 13:39:30 Host identity created.
20.03.2014, 13:40:24 Gauner uses modified data file
20.03.2014, 13:40:24 BattlEye Server: Player #0 Gauner (77.21.51.13:2304) connected
20.03.2014, 13:40:24 Player Gauner connecting.
20.03.2014, 13:40:24 Mission DayZ Epoch Napf read from bank.
20.03.2014, 13:40:53 BattlEye Server: Initialized (v1.185)
20.03.2014, 13:40:53 Host identity created.
20.03.2014, 13:42:16 Gauner uses modified data file
20.03.2014, 13:42:16 BattlEye Server: Player #0 Gauner (77.21.51.13:2304) connected
20.03.2014, 13:42:16 Player Gauner connecting.
20.03.2014, 13:42:16 Mission DayZ Epoch Napf read from bank.
```

Wie man sieht, stürzt er immer nachdem ein Spieler auf den Server kommt ab, sobald er die "bank" lesen will.

Daber erhält der Server ein ERROR mit der Zeile

```
expCond="(player distance Lenz) < 50;";
```

aus der oben benannten class.

Wir können dabei vermuten, dass es sich in der Zeile um die definition des Wirkungsumkreises handelt.

**Comment by JPPWeber** [comment]
Die Mission wuerde ich aus dem Epoch-Server Paket nehmen.
Ich musste bei mir nicht entfernen, deswegen wunder ich mich.

**Comment by AnnoDomine** [comment]
Wir müssen hier definieren, dass wir nicht Chenarus sondern Napf nutzen.

Es ist leider auch keine Mission, sondern der Wirkungskreis eines Traders.

**Comment by JPPWeber** [comment]
Aber die Scripte dafuer liegen in der Mission meines Wissens

**Comment by AnnoDomine** [comment]
Richtig und wenn ich die Mission rausschmeiße, funzt ja erstmal nix. Das Merkwürdige dabei ist, dass diese Zeile/n genau gleich geschrieben sind, wie in der Original Chanrus mission.sqm innerhalb der pbo

Meinst du diese Datei?

Wann währst du heute Abend im TS? Damit ich und Nanakie mal joinen.

**Comment by JPPWeber** [comment]
In der SQM findest du im Normalfall keine Scripte sondern drumherum in den Ordner.

Wann ich heute Abend da bin weiss ich noch nicht genau, muss heute bis 18 Uhr arbeiten :/

**Comment by AnnoDomine** [comment]
Ich habe da nur einen Orner:

dayz_epoch_24.napf\ca\modules\functions

Dort ist eine init.sqf datei,

#include "\z\addons\dayz_code\system\ca\functions\init.sqf"

mehr steht nicht drin.

ansonsten sind noch die Daten 

discription.ext
init.sqf
mission.sqm
server_trader.sqf

Daten in der pbo drin.

**Comment by AnnoDomine** [comment]
Wir versuchen es später mal mit der Original Chenarus-Map und gucken uns das dort an.

**Comment by JPPWeber** [comment]
Chernarus brauch A2 Content, denk dran ;)

**Comment by Nanakie** [comment]
so eben mit der chenarus map versucht und funtkioniert soweit alles jetzt nurnoch rausfinden wiro napf rummuckt

**Comment by JPPWeber** [comment]
Nimm die Napf aus dem Epoche Server von deren hp
Am 20.03.2014 20:18 schrieb "Nanakie" notifications@github.com:

**Comment by Nanakie** [comment]
ich bin nur der admin habe so mit dayz nix am hut haste mal eben nen link zu?

**Comment by JPPWeber** [comment]
Bin sofort im TS. Jppweber.de
Am 20.03.2014 20:24 schrieb "Nanakie" notifications@github.com:

**Comment by AnnoDomine** [comment]
Wir haben uns nun entschieden, den Server auf Panthera 2 laufen zu lassen, da Napf nicht funktioniert und die Leute ungeduldig werden. Ich dank dir JPP für deine Hilfe. Man erschießt sich ingame :D
