### ISSUE TITLE
Ask 4 options

### ISSUE THREAD

**Issue by AnnoDomine** [denisio/Dayz-Epoch-Linux-Server#16]
I have now install my DayZ Epoch Chernarus Server with a few Scripts.

Now i want to change some options.
1. I want that the server restart automatic after 6 houres run. How i can do this?
2. At the first 4 1/2 houres i want daytime (3 pm till 7:30 pm) then 1/2 houre sunset (7:30 pm till 8 pm) and the last houre night (8 pm till 9 pm).

TY for ure help!

**Comment by MINORITYmaN** [comment]
how about cron job?

**Comment by AnnoDomine** [comment]
kk
with cronjob i do it now. but my second ask?

**Comment by AnnoDomine** [comment]
Fixed
