### ISSUE TITLE
Buildings and Cars away after restart.

### ISSUE THREAD

**Issue by AnnoDomine** [denisio/Dayz-Epoch-Linux-Server#19]
I running my DayZ Epoch Server since two weeks and since a restart all buildings from players and buied cars are away. In the DB the Objects are there but not in Game. We have do so much that we find over google but nothing has fix the issius.
We think that arma not read the DB after restart anymore.
2 Weeks without issius and then that

:(

Need pls fast help. over 20 player waiting for the server.

**Comment by denisio** [comment]
Hello,

Please, post your "dump.log".

**Comment by AnnoDomine** [comment]
I upload the Logs from the last 5 Days on our root-server.
You can download it in rar data from here >

http://www.kdfw.de.vu/Administartorendateien/DayZ_Epoch_Server_Logs170404-220404.rar

We have install Mods but thre problem is not from there becouse i installed the last mod 1 week befor.

We test it on our test-virtual-server with vanilla and mods and with reset of the db and the cashe. All with the same problem.

I test it so:
1. I bought a 30 Pole and a wall and place that -> restart -> pole and wall no more there were i placed.
2. I bought a car > restart > car is away but key is in inventar.

We checked the db and the pbo for hacking > nothing

We clean the db from ObjectID = 0 and Inventar = "nothing" - datas > not solve

With my Post i closed the Server with a password.

When u want i can show the problem directly on my server.

**Comment by AnnoDomine** [comment]
`We test it on our test-virtual-server with vanilla and mods and with reset of the db and the cashe. All with the same problem`

I mean each seperatly.

**Comment by denisio** [comment]
You have corrupted the Hitpoints in Object_DATA.

How to fix it:
1) Run into mysql console: alter table Object_DATA MODIFY COLUMN Hitpoints varchar(4096) NOT NULL DEFAULT '[]';
2) Run fix_objects.pl (from git repo).

**Comment by AnnoDomine** [comment]
Problem solved. Thank u for ure fast help.

**Comment by AnnoDomine** [comment]
I reopen the Issius becouse since the DB update we have a new problem.

U cant buy cars or other vehicles.

It means u go to a trader 4 vehicles and want to buy a vehicle.
U get the key but no vehicle spawn and u dont pay.
The second problem is that i cant spawn a vehicle as admin.

Her is the DUMB.LOG-Entry:

```
21:24:42 "PUBLISH: Attempt 3965a0c0# 1071848: arrow_down_large_ep1.p3d REMOTE"
21:24:42 "CHILD:308:11:SUV_Camo:0:5177:[285,[6292.99,7806.43,0.000152588]]:[]:[]:1:629307806407120:"
21:24:42 "LOAD OBJECT ID: \cache\objects\629307806407120.sqf"
21:24:42 Warning Message: Script cache\objects\629307806407120.sqf not found
21:24:42 "OBJECT ID CACHE: "
21:24:42 "OBJECT ID NOT FOUND"
21:24:42 "CUSTOM: failed to get id for : "629307806407120""
```

**Comment by denisio** [comment]
Please, update "https://github.com/denisio/Dayz-Epoch-Linux-Server/blob/master/%40dayz_epoch_server/addons/dayz_server.pbo"
