### ISSUE TITLE
Silent crash when mission loads

### ISSUE THREAD

**Issue by SolSoCoG** [denisio/Dayz-Epoch-Linux-Server#23]
Hey, since doing some counterproductive stuff in terms of gameserver performance, the epoch server shuts down without any notice (or RPT/log entry) when a player joins/mission loads.

I changed the following features of the kernel:
I changed from CompletelyFairScheduler to BrainFuckScheduler and from CompletelyFairQueueing to DEADLINEScheduler,
I also changed the default clock from 1000HZ to 100HZ, removed PREEMPT and set the tick to oldskool periodic.

Somebody knows what could cause such bad behaviour? Other gameservers handle it pretty well.

Edit:
After 4 servercrashes the server managed to load the mission file. Though it was still weird.

Also, the first bought car after restart vanish and appears after map reload, inventory is getting wiped randomly etc etc. Thanks for the server so far ;).

**Comment by denisio** [comment]
Welcome to http://forums.bistudio.com/showthread.php?146816-ARMA-2-Operation-Arrowhead-Linux-Server-beta-1-62-102451. It is not supported.
