### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Warface** [denisio/Dayz-Epoch-Linux-Server#3]
I have this error when I run ./epoch.sh

```
Segmentation fault      (core dumped) | ./writer.pl
```

What could it be ?

**Comment by denisio** [comment]
What is OS ?

Try to run:
$ ldd epoch

**Comment by Warface** [comment]
CentOS

Result of $ ldd epoch

```
./epoch: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./epoch)
        linux-gate.so.1 =>  (0x009a8000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00568000)
        libm.so.6 => /lib/libm.so.6 (0x00d8f000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x007ec000)
        libdl.so.2 => /lib/libdl.so.2 (0x008e9000)
        librt.so.1 => /lib/librt.so.1 (0x00b79000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00b08000)
        libc.so.6 => /lib/libc.so.6 (0x002a2000)
        /lib/ld-linux.so.2 (0x00280000)
```

Seems to be the version of my libstdc++.so.6 that is not up to date. But can't find any RPM or YUM for it. Do you any clue how to update it on CentOS ?

**Comment by JPPWeber** [comment]
The Problem is, that CentOS is very conservertive with their repos.

They are always a bit behind, because they only use rock solid programs and libraries

**Comment by WopperTheCat** [comment]
Had the same problem on a test server and managed to solve the problem with cpan. Now my server works like a charm.

**Comment by Warface** [comment]
Could you tell us how you managed to solve it ?

**Comment by SolSoCoG** [comment]
You go to  http://www.fabrik17.de/files/starbound-server-x32-libdeps.tar.gz
unpack it, and put everything:
libc.so.6, libdl.so.2, libfreetype.so.6, libgcc_s.so.1, libm.so.6, libpng12.so.0, libpthread.so.0, libstdc++.so.6, libz.so.1
and
ld-linux.so.2 into the epoch folder.

Then you edit the epoch.sh and add ./ld-linux.so.2 --library-path ./ in front of ./epoch looking like this:
./ld-linux.so.2 --library-path ./ ./epoch -server -mod="@dayz_epoch;@dayz_epoch_server;" -config="cfgdayz/server.cfg" [...]

After you've done that, it works.

**Comment by Warface** [comment]
Thanks but I've lost faith and uninstalled it and quit playing the game :D
