### ISSUE TITLE
Cache Saving not work properly

### ISSUE THREAD

**Issue by pixlcrashr** [denisio/Dayz-Epoch-Linux-Server#30]
Hello,

My Cache only get saved after proper disconnecting. 1min(and 10-5min) before a restart, my Position and Skin wouldn't get saved.
So, got someone helpful answers?

Is it practical to add a writer.pl crontask 1 min before a restart?

**Comment by deannreid** [comment]
I'd recommend setting up restart messages https://github.com/deannreid/BattlEye-RCON-Control-PHP
because as far as I know, not tested anything. there isn't an easy way to sort that.

**Comment by pixlcrashr** [comment]
@deannreid I do and I've a shortened Version of this script with random messages(self-cutted/coded). But the Playerinventory get not saved at restart. Cars, Bases and Co. get saved.

But this PlayerInvs...

EDIT:
Or is there no way to save at very restart? So the Players should log out at 5Mins?

**Comment by deannreid** [comment]
Rule of thumb for me is 10 minutes before restart to make sure, just do a few tests I'll have a look and see what I can find to force a save of inventory's, I myself have never had this problem, not for a long time anyway

**Comment by pixlcrashr** [comment]
I'll see, thanks.

**Comment by pixlcrashr** [comment]
Seems to work,

Thanks again
