### ISSUE TITLE
server.cfg not being read

### ISSUE THREAD

**Issue by piercy** [denisio/Dayz-Epoch-Linux-Server#8]
Hi, my server.cfg is not being read, the host name doesnt change.  I believe this is also causing an issue where you have to vote for the mission when you start and causing it to not authenticate. 

any ideas?

**Comment by JPPWeber** [comment]
Have you checked you path?

Absolute path is a good one.
/home/epoch/profiles/server123456.cfg

Linux is casesensitive ... lower and upper symbols

Are the permissions set right?
