### ISSUE TITLE
server not read beserver.cfg

### ISSUE THREAD

**Issue by netinsideout** [denisio/Dayz-Epoch-Linux-Server#9]
I just found, that rcon password is default on my dayz epoch server. Server not read battleye configuration file: beserver.cfg 

Work around:
Add following start parameter in epoch.sh with absolute path to your server battleye folder. Relative path not worked.

Example:
-bepath="/home/dayz/dayz-epoch-1.0.4.2/cfgdayz/battleye"

**Comment by JPPWeber** [comment]
As told in the config.cfg not found issue, you should always tell a programm the absolute path.

**Comment by denisio** [comment]
epoch/expansion/battleye/beserver.cfg
